//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleUsingAdoDotNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleDetail
    {
        public int PKVehicleId { get; set; }
        public string TypeOfVehicle { get; set; }
        public int RegNo { get; set; }
        public System.DateTime DateOfManufacture { get; set; }
        public string Color { get; set; }
        public string Make { get; set; }
        public decimal Price { get; set; }
    }
}
